const FAKE_GENERIC_NAME = 'any_name';
const FAKE_GENERIC_CPF = 'valid_cpf';
const FAKE_GENERIC_PASSWORD = 'any_password';
const FAKE_GENERIC_EMAIL = 'test@gmail.com';
const FAKE_ACCESS_TOKEN = 'access_token';
const INVALID_FAKE_GENERIC_CPF = 'invalid_cpf';
const INVALID_FAKE_ACCESS_TOKEN = null;
const INVALID_FAKE_GENERIC_PASSWORD = 'invalid_password';
const INVALID_FAKE_GENERIC_EMAIL = 'invalid_test@gmail.com';

// Login Router
const LOGIN_ROUTER_SUT_AUTH_USE_CASE_WITH_NO_PASSWORD_ERROR = Symbol(
  'LOGIN_ROUTER_SUT_AUTH_USE_CASE_WITH_NO_PASSWORD_ERROR',
);
const LOGIN_ROUTER_SUT_AUTH_USE_CASE_WITH_NO_EMAIL_ERROR = Symbol(
  'LOGIN_ROUTER_SUT_AUTH_USE_CASE_WITH_NO_EMAIL_ERROR',
);
const LOGIN_ROUTER_SUT_AUTH_USE_CASE_THROWING_SERVER_ERROR = Symbol(
  'LOGIN_ROUTER_SUT_AUTH_USE_CASE_THROWING_SERVER_ERROR',
);
const LOGIN_ROUTER_SUT_AUTH_USE_CASE_THROWING_MONGO_CONNECTION_ERROR = Symbol(
  'LOGIN_ROUTER_SUT_AUTH_USE_CASE_THROWING_MONGO_CONNECTION_ERROR',
);
const LOGIN_ROUTER_SUT_AUTH_USE_CASE_THROWING_MONGO_CLOSE_ERROR = Symbol(
  'LOGIN_ROUTER_SUT_AUTH_USE_CASE_THROWING_MONGO_CLOSE_ERROR',
);
const LOGIN_ROUTER_SUT_EMAIL_VALIDATOR_THROWING_ERROR = Symbol(
  'LOGIN_ROUTER_SUT_EMAIL_VALIDATOR_THROWING_ERROR',
);

const FAKE_SIGN_UP_HTTP_REQUEST = {
  body: {
    email: FAKE_GENERIC_EMAIL,
    password: FAKE_GENERIC_PASSWORD,
    cpf: FAKE_GENERIC_CPF,
    name: FAKE_GENERIC_NAME,
  },
};
const INVALID_FAKE_SIGN_UP_HTTP_REQUEST_WITH_NO_EMAIL = {
  body: {
    password: FAKE_GENERIC_PASSWORD,
    cpf: FAKE_GENERIC_CPF,
    name: FAKE_GENERIC_NAME,
  },
};
const INVALID_FAKE_SIGN_UP_HTTP_REQUEST_WITH_NO_PASSWORD = {
  body: {
    email: FAKE_GENERIC_EMAIL,
    cpf: FAKE_GENERIC_CPF,
    name: FAKE_GENERIC_NAME,
  },
};
const INVALID_FAKE_SIGN_UP_HTTP_REQUEST_WITH_NO_CPF = {
  body: {
    email: FAKE_GENERIC_EMAIL,
    password: FAKE_GENERIC_PASSWORD,
    name: FAKE_GENERIC_NAME,
  },
};

const INVALID_FAKE_SIGN_UP_HTTP_REQUEST_WITH_NO_NAME = {
  body: {
    email: FAKE_GENERIC_EMAIL,
    password: FAKE_GENERIC_PASSWORD,
    cpf: FAKE_GENERIC_CPF,
  },
};

const FAKE_SIGN_UP_HTTP_REQUEST_WITH_INVALID_EMAIL = {
  body: {
    email: INVALID_FAKE_GENERIC_EMAIL,
    password: FAKE_GENERIC_PASSWORD,
    cpf: FAKE_GENERIC_CPF,
    name: FAKE_GENERIC_NAME,
  },
};
const FAKE_SIGN_UP_HTTP_REQUEST_WITH_INVALID_CPF = {
  body: {
    email: FAKE_GENERIC_EMAIL,
    password: FAKE_GENERIC_PASSWORD,
    cpf: INVALID_FAKE_GENERIC_CPF,
    name: FAKE_GENERIC_NAME,
  },
};
const FAKE_HTTP_REQUEST_WITH_EMAIL_ALREADY_INSERTED = {
  body: {
    email: FAKE_GENERIC_EMAIL,
    password: FAKE_GENERIC_PASSWORD,
    cpf: FAKE_GENERIC_CPF,
    name: FAKE_GENERIC_NAME,
  },
};
const FAKE_HTTP_REQUEST_WITH_INVALID_EMAIL_AND_VALID_PASSWORD = {
  body: {
    email: INVALID_FAKE_GENERIC_EMAIL,
    password: FAKE_GENERIC_PASSWORD,
  },
};
const INVALID_FAKE_EMPTY_HTTP_REQUEST = {};

const SIGN_UP_USE_CASE_THROWING_SERVER_ERROR_SUT =
  'SIGN_UP_USE_CASE_THROWING_SERVER_ERROR_SUT';
const EMAIL_VALIDATOR_THROWING_ERROR_SUT = 'EMAIL_VALIDATOR_THROWING_ERROR_SUT';
const CPF_VALIDATOR_THROWING_ERROR_SUT = 'CPF_VALIDATOR_THROWING_ERROR_SUT';

module.exports = {
  LOGIN_ROUTER_SUT_AUTH_USE_CASE_WITH_NO_PASSWORD_ERROR,
  LOGIN_ROUTER_SUT_AUTH_USE_CASE_WITH_NO_EMAIL_ERROR,
  LOGIN_ROUTER_SUT_AUTH_USE_CASE_THROWING_SERVER_ERROR,
  LOGIN_ROUTER_SUT_AUTH_USE_CASE_THROWING_MONGO_CONNECTION_ERROR,
  LOGIN_ROUTER_SUT_AUTH_USE_CASE_THROWING_MONGO_CLOSE_ERROR,
  LOGIN_ROUTER_SUT_EMAIL_VALIDATOR_THROWING_ERROR,
  FAKE_GENERIC_NAME,
  FAKE_GENERIC_CPF,
  FAKE_GENERIC_PASSWORD,
  FAKE_GENERIC_EMAIL,
  FAKE_ACCESS_TOKEN,
  INVALID_FAKE_ACCESS_TOKEN,
  INVALID_FAKE_GENERIC_PASSWORD,
  INVALID_FAKE_GENERIC_EMAIL,
  INVALID_FAKE_GENERIC_CPF,
  FAKE_HTTP_REQUEST_WITH_INVALID_EMAIL_AND_VALID_PASSWORD,
  FAKE_SIGN_UP_HTTP_REQUEST_WITH_INVALID_EMAIL,
  FAKE_SIGN_UP_HTTP_REQUEST_WITH_INVALID_CPF,
  INVALID_FAKE_SIGN_UP_HTTP_REQUEST_WITH_NO_CPF,
  INVALID_FAKE_SIGN_UP_HTTP_REQUEST_WITH_NO_EMAIL,
  INVALID_FAKE_SIGN_UP_HTTP_REQUEST_WITH_NO_PASSWORD,
  INVALID_FAKE_SIGN_UP_HTTP_REQUEST_WITH_NO_NAME,
  INVALID_FAKE_EMPTY_HTTP_REQUEST,
  EMAIL_VALIDATOR_THROWING_ERROR_SUT,
  FAKE_SIGN_UP_HTTP_REQUEST,
  FAKE_HTTP_REQUEST_WITH_EMAIL_ALREADY_INSERTED,
  CPF_VALIDATOR_THROWING_ERROR_SUT,
  SIGN_UP_USE_CASE_THROWING_SERVER_ERROR_SUT,
};
