/**
 * Login Router
 */
const LOGIN_ROUTER_SUT_AUTH_USE_CASE_WITH_NO_PASSWORD_ERROR = Symbol(
  'LOGIN_ROUTER_SUT_AUTH_USE_CASE_WITH_NO_PASSWORD_ERROR',
);
const LOGIN_ROUTER_SUT_AUTH_USE_CASE_WITH_NO_EMAIL_ERROR = Symbol(
  'LOGIN_ROUTER_SUT_AUTH_USE_CASE_WITH_NO_EMAIL_ERROR',
);
const LOGIN_ROUTER_SUT_AUTH_USE_CASE_THROWING_SERVER_ERROR = Symbol(
  'LOGIN_ROUTER_SUT_AUTH_USE_CASE_THROWING_SERVER_ERROR',
);
const LOGIN_ROUTER_SUT_AUTH_USE_CASE_THROWING_MONGO_CONNECTION_ERROR = Symbol(
  'LOGIN_ROUTER_SUT_AUTH_USE_CASE_THROWING_MONGO_CONNECTION_ERROR',
);
const LOGIN_ROUTER_SUT_AUTH_USE_CASE_THROWING_MONGO_CLOSE_ERROR = Symbol(
  'LOGIN_ROUTER_SUT_AUTH_USE_CASE_THROWING_MONGO_CLOSE_ERROR',
);
const LOGIN_ROUTER_SUT_EMAIL_VALIDATOR_THROWING_ERROR = Symbol(
  'LOGIN_ROUTER_SUT_EMAIL_VALIDATOR_THROWING_ERROR',
);

/**
 * Sign Up Router
 */
const SIGN_UP_ROUTER_SUT_SIGN_UP_USE_CASE_THROWING_SERVER_ERROR = Symbol(
  'SIGN_UP_ROUTER_SUT_SIGN_UP_USE_CASE_THROWING_SERVER_ERROR',
);
const SIGN_UP_ROUTER_SUT_EMAIL_VALIDATOR_THROWING_ERROR = Symbol(
  'SIGN_UP_ROUTER_SUT_EMAIL_VALIDATOR_THROWING_ERROR',
);
const SIGN_UP_ROUTER_SUT_CPF_VALIDATOR_THROWING_ERROR = Symbol(
  'SIGN_UP_ROUTER_SUT_CPF_VALIDATOR_THROWING_ERROR',
);

/**
 * Logout Router
 */
const LOGOUT_ROUTER_SUT_TOKEN_VALIDATOR_NO_TOKEN_ERROR = Symbol(
  'LOGOUT_ROUTER_SUT_TOKEN_VALIDATOR_NO_TOKEN_ERROR',
);

module.exports = {
  LOGIN_ROUTER_SUT_AUTH_USE_CASE_WITH_NO_PASSWORD_ERROR,
  LOGIN_ROUTER_SUT_AUTH_USE_CASE_WITH_NO_EMAIL_ERROR,
  LOGIN_ROUTER_SUT_AUTH_USE_CASE_THROWING_SERVER_ERROR,
  LOGIN_ROUTER_SUT_AUTH_USE_CASE_THROWING_MONGO_CONNECTION_ERROR,
  LOGIN_ROUTER_SUT_AUTH_USE_CASE_THROWING_MONGO_CLOSE_ERROR,
  LOGIN_ROUTER_SUT_EMAIL_VALIDATOR_THROWING_ERROR,
  SIGN_UP_ROUTER_SUT_SIGN_UP_USE_CASE_THROWING_SERVER_ERROR,
  SIGN_UP_ROUTER_SUT_EMAIL_VALIDATOR_THROWING_ERROR,
  SIGN_UP_ROUTER_SUT_CPF_VALIDATOR_THROWING_ERROR,
  LOGOUT_ROUTER_SUT_TOKEN_VALIDATOR_NO_TOKEN_ERROR,
};
