const FAKE_GENERIC_EMAIL = 'test@gmail.com';
const FAKE_GENERIC_PASSWORD = 'any_password';

const LOAD_USER_BY_EMAIL_REPOSITORY_WITH_ERROR_SUT =
  'LOAD_USER_BY_EMAIL_REPOSITORY_WITH_ERROR_SUT';
const ENCRYPTER_WITH_ERROR_SUT = 'ENCRYPTER_WITH_ERROR_SUT';
const TOKEN_GENERATOR_WITH_ERROR_SUT = 'TOKEN_GENERATOR_WITH_ERROR_SUT';
const UPDATE_ACCESS_TOKEN_REPOSITORY_WITH_ERROR_SUT =
  'UPDATE_ACCESS_TOKEN_REPOSITORY_WITH_ERROR_SUT';

/**
 * Sign Up Use Case
 */
const SIGN_UP_USE_CASE_SUT_LOAD_USER_BY_EMAIL_REPOSITORY_WITH_ERROR = Symbol(
  'SIGN_UP_USE_CASE_SUT_LOAD_USER_BY_EMAIL_REPOSITORY_WITH_ERROR',
);
const SIGN_UP_USE_CASE_SUT_ENCRYPTER_WITH_ERROR = Symbol(
  'SIGN_UP_USE_CASE_SUT_ENCRYPTER_WITH_ERROR',
);
const SIGN_UP_USE_CASE_SUT_INSERT_USER_REPOSITORY_WITH_ERROR = Symbol(
  'SIGN_UP_USE_CASE_SUT_INSERT_USER_REPOSITORY_WITH_ERROR',
);
const SIGN_UP_USE_CASE_SUT_TOKEN_GENERATOR_WITH_ERROR = Symbol(
  'SIGN_UP_USE_CASE_SUT_TOKEN_GENERATOR_WITH_ERROR',
);
const SIGN_UP_USE_CASE_SUT_UPDATE_ACCESS_TOKEN_REPOSITORY_WITH_ERROR = Symbol(
  'SIGN_UP_USE_CASE_SUT_UPDATE_ACCESS_TOKEN_REPOSITORY_WITH_ERROR',
);

module.exports = {
  FAKE_GENERIC_EMAIL,
  FAKE_GENERIC_PASSWORD,
  LOAD_USER_BY_EMAIL_REPOSITORY_WITH_ERROR_SUT,
  ENCRYPTER_WITH_ERROR_SUT,
  TOKEN_GENERATOR_WITH_ERROR_SUT,
  UPDATE_ACCESS_TOKEN_REPOSITORY_WITH_ERROR_SUT,
  SIGN_UP_USE_CASE_SUT_LOAD_USER_BY_EMAIL_REPOSITORY_WITH_ERROR,
  SIGN_UP_USE_CASE_SUT_ENCRYPTER_WITH_ERROR,
  SIGN_UP_USE_CASE_SUT_INSERT_USER_REPOSITORY_WITH_ERROR,
  SIGN_UP_USE_CASE_SUT_TOKEN_GENERATOR_WITH_ERROR,
  SIGN_UP_USE_CASE_SUT_UPDATE_ACCESS_TOKEN_REPOSITORY_WITH_ERROR,
};
