const FAKE_GENERIC_EMAIL = 'test@gmail.com'
const INVALID_FAKE_GENERIC_EMAIL = 'invalid_test@gmail.com'

const LOAD_USER_BY_EMAIL_REPOSITORY_EMPTY_SUT = 'LOAD_USER_BY_EMAIL_REPOSITORY_EMPTY_SUT'
const LOAD_USER_BY_EMAIL_REPOSITORY_EMPTY_OBJECT_SUT = 'LOAD_USER_BY_EMAIL_REPOSITORY_EMPTY_OBJECT_SUT'

module.exports = {
  FAKE_GENERIC_EMAIL,
  INVALID_FAKE_GENERIC_EMAIL,
  LOAD_USER_BY_EMAIL_REPOSITORY_EMPTY_SUT,
  LOAD_USER_BY_EMAIL_REPOSITORY_EMPTY_OBJECT_SUT
}
