const MONGO_ATTEMPTS_TO_RETRY = 3;
const MONGO_FAKE_URI = 'any_uri';
const MONGO_FAKE_DATABASE_NAME = 'any_database';

const MONGO_HELPER_WITH_EMPTY_ARGS_SUT = 'MONGO_HELPER_WITH_EMPTY_ARGS_SUT';
const MONGO_HELPER_WITH_ARGS_SUT = 'MONGO_HELPER_WITH_ARGS_SUT';

const FAKE_GENERIC_USER_ID = 'any_user_id';
const FAKE_GENERIC_ACCESS_TOKEN = 'any_token';
const FAKE_GENERIC_EMAIL = 'test@gmail.com';
const FAKE_GENERIC_PASSWORD = 'any_password';
const INVALID_FAKE_GENERIC_EMAIL = 'invalid_test@gmail.com';

const LOAD_USER_BY_EMAIL_REPOSITORY_EMPTY_SUT =
  'LOAD_USER_BY_EMAIL_REPOSITORY_EMPTY_SUT';
const LOAD_USER_BY_EMAIL_REPOSITORY_EMPTY_OBJECT_SUT =
  'LOAD_USER_BY_EMAIL_REPOSITORY_EMPTY_OBJECT_SUT';
const LOAD_USER_BY_EMAIL_REPOSITORY_WITH_EMPTY_USER_MODEL_OBJECT_SUT =
  'LOAD_USER_BY_EMAIL_REPOSITORY_WITH_EMPTY_USER_MODEL_OBJECT_SUT';

const UPDATE_ACCESS_TOKEN_REPOSITORY_EMPTY_SUT =
  'UPDATE_ACCESS_TOKEN_REPOSITORY_EMPTY_SUT';
const UPDATE_ACCESS_TOKEN_REPOSITORY_EMPTY_OBJECT_SUT =
  'UPDATE_ACCESS_TOKEN_REPOSITORY_EMPTY_OBJECT_SUT';
const UPDATE_ACCESS_TOKEN_REPOSITORY_WITH_EMPTY_USER_MODEL_OBJECT_SUT =
  'UPDATE_ACCESS_TOKEN_REPOSITORY_WITH_EMPTY_USER_MODEL_OBJECT_SUT';

module.exports = {
  MONGO_ATTEMPTS_TO_RETRY,
  MONGO_FAKE_URI,
  MONGO_FAKE_DATABASE_NAME,
  MONGO_HELPER_WITH_EMPTY_ARGS_SUT,
  MONGO_HELPER_WITH_ARGS_SUT,
  FAKE_GENERIC_USER_ID,
  FAKE_GENERIC_ACCESS_TOKEN,
  FAKE_GENERIC_EMAIL,
  FAKE_GENERIC_PASSWORD,
  INVALID_FAKE_GENERIC_EMAIL,
  LOAD_USER_BY_EMAIL_REPOSITORY_EMPTY_SUT,
  LOAD_USER_BY_EMAIL_REPOSITORY_EMPTY_OBJECT_SUT,
  LOAD_USER_BY_EMAIL_REPOSITORY_WITH_EMPTY_USER_MODEL_OBJECT_SUT,
  UPDATE_ACCESS_TOKEN_REPOSITORY_EMPTY_SUT,
  UPDATE_ACCESS_TOKEN_REPOSITORY_EMPTY_OBJECT_SUT,
  UPDATE_ACCESS_TOKEN_REPOSITORY_WITH_EMPTY_USER_MODEL_OBJECT_SUT,
};
