const MONGO_ATTEMPTS_TO_RETRY = 3
const MONGO_FAKE_URI = 'any_uri'
const MONGO_FAKE_DATABASE_NAME = 'any_database'

const MONGO_HELPER_WITH_EMPTY_ARGS_SUT = 'MONGO_HELPER_WITH_EMPTY_ARGS_SUT'
const MONGO_HELPER_WITH_ARGS_SUT = 'MONGO_HELPER_WITH_ARGS_SUT'

const FAKE_GENERIC_EMAIL = 'test@gmail.com'
const INVALID_FAKE_GENERIC_EMAIL = 'invalid_test@gmail.com'

const LOAD_USER_BY_EMAIL_REPOSITORY_EMPTY_SUT = 'LOAD_USER_BY_EMAIL_REPOSITORY_EMPTY_SUT'
const LOAD_USER_BY_EMAIL_REPOSITORY_EMPTY_OBJECT_SUT = 'LOAD_USER_BY_EMAIL_REPOSITORY_EMPTY_OBJECT_SUT'

module.exports = {
  MONGO_ATTEMPTS_TO_RETRY,
  MONGO_FAKE_URI,
  MONGO_FAKE_DATABASE_NAME,
  MONGO_HELPER_WITH_EMPTY_ARGS_SUT,
  MONGO_HELPER_WITH_ARGS_SUT,
  FAKE_GENERIC_EMAIL,
  INVALID_FAKE_GENERIC_EMAIL,
  LOAD_USER_BY_EMAIL_REPOSITORY_EMPTY_SUT,
  LOAD_USER_BY_EMAIL_REPOSITORY_EMPTY_OBJECT_SUT
}
